In [1]:
import numpy as np 

что-то к чаю

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
a= np.array([1, 4, 7, 19])
a

array([ 1,  4,  7, 19])

In [13]:
a[2]

np.int64(7)

In [15]:
a[2] = 155

In [16]:
a

array([  1,   4, 155,  19])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

In [25]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
n[0,1]

np.int64(2)

In [27]:
n[0,1] = 10

In [28]:
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Получаем колонку:

In [30]:
n[:, 1]

array([10,  5,  8])

In [31]:
n[:, 1] = [9, 19, 99]

In [32]:
n

array([[ 1,  9,  3],
       [ 4, 19,  6],
       [ 7, 99,  9]])

In [37]:
np.random.seed (2)
np.random.rand (5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [40]:
np.random.seed (2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element wise operation

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
a + 1

array([1, 2, 3, 4, 5])

In [45]:
a * 100

array([  0, 100, 200, 300, 400])

In [48]:
a / 1

array([0., 1., 2., 3., 4.])

In [49]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [50]:
10 + (a*2)

array([10, 12, 14, 16, 18])

In [51]:
b = 10 + (a * 2) ** 2

In [52]:
b

array([10, 14, 26, 46, 74])

In [53]:
a + b

array([10, 15, 28, 49, 78])

Comparison operation

In [54]:
a

array([0, 1, 2, 3, 4])

In [55]:
a >= 2

array([False, False,  True,  True,  True])

In [56]:
a > b

array([False, False, False, False, False])

In [57]:
b > a

array([ True,  True,  True,  True,  True])

In [58]:
a[a >= 2]

array([2, 3, 4])

In [59]:
c = a[a >= 2]

In [60]:
c

array([2, 3, 4])

Summarizing operations

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.min()

np.int64(0)

In [63]:
a.max()


np.int64(4)

In [64]:
a.sum()

np.int64(10)

In [65]:
a.mean()

np.float64(2.0)